[package]
name = "turtle-lib-macroquad"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
macroquad = "0.4"
earcutr = "0.5"
tween = "2.1.0"

[dev-dependencies]
# For examples and testing
