[package]
name = "turtle-lib-macroquad"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
macroquad = "0.4"
tween = "2.1.0"
lyon = "1.0"

[dev-dependencies]
# For examples and testing
